import time
while True:
  time.sleep(3)
  print ' _    _                           ____  _      _   _         _             '
  print '| |  | |                         |  _ \(_)    | | | |       | |            '
  print '| |__| | __ _ _ __  _ __  _   _  | |_) |_ _ __| |_| |__   __| | __ _ _   _ '
  print '|  __  |/ _` |  _ \| _  \| | | | |  _ <| |  __| __|  _  \/    |/ _  | | | |'
  print '| |  | | (_| | |_) | |_) | |_| | | |_) | | |  | |_| | | | (_| | (_| | |_| |'
  print '|_|  |_|\__,_| .__/| .__/ \__, | |____/|_|_|   \__|_| |_|\__,_|\__,_|\__, |'
  print '             | |   | |     __/ |                                      __/ |'
  print '             |_|   |_|    |___/                                      |___/ '




  time.sleep(3)
  print ' _____          _____  ______      _ '
  print '|  __ \   /\   |  __ \|  __ \ \   / /'
  print '| |  | | /  \  | |  | | |  | \ \_/ / '
  print '| |  | |/ /\ \ | |  | | |  | |\   /  '
  print '| |__| / ____ \| |__| | |__| | | |   '
  print '|_____/_/    \_\_____/|_____/  |_|   '
  
  time.sleep(3)
  print '                                                  '
  print '                                                  '
  print '                     /^\                         '
  #print '                                                 '
  print '           /         (/^\)     /                 '
  #print '                                                 '
  print '      \   ( \         \ /     ( \     /^\        '
  #print '                                                 '
  print '     / )   \ |        _|_      \ |   |/^\|       '
  #print '                                                 '
  print '    | /    _|_        | |      _|_    \ /        '
  #print '                                                 '
  print '    _|_    | |        | |      | |    _|_        '
  #print '                                                 '
  print '    | |    | |        | |      | |    | |        '
  #print '                                                 '
  print '    | |    | |    ****| |******| |    | |        '
  #print '                                                 ' 
  print '    | |****| |****    | |      | |****| |        '
  #print '                                                 '
  print '   *| |    | |                 | |    | |*****   '
  #print '                                                 '
  print ' *  | |   H  A  P  P  Y               | |      * '
  #print '                                                 '
  print '*                                               *'
  #print '                                                 '
  print '| *            B  I  R  T  H  D  A  Y  !      * | ' 
  #print '                                                 '
  print '|  *****                                 *****  |'
  #print '                   D  A  D  D  Y                 '
  print '|@      **********  D  A  D  D  Y   ********** @|'
  #print '                                                 '
  print '| @   @           *************           @   @ |'
  #print '                                                 '
  print '|  @@@ @    @                       @    @ @@@  |'
  #print '                                                 '        
  print '|       @@@@ @      @       @      @ @@@@       |'
  #print '                                                 '
  print ' *            @@@@@@ @     @ @@@@@@            * '
  #print '                                                 '
  print '  *                   @@@@@                   *  '
  #print '                                                 '
  print '   *****                                 *****   '
  #print '                                                 '
  print '        **********             **********        '
  #print '                                                 '
  print '                  *************                  '
